### ISSUE TITLE
java.net.BindException: bind(2) error: Invalid argument when trying to bind to '/run/hadoop-hdfs/dn_socket'

### ISSUE THREAD

**Issue by fithisux** [hadoop-sandbox/hadoop-sandbox#1] opened 2022-02-07 12:38 UTC
I am on Mac

Darwin C02CH2W2MD6R.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

with latest docker desktop
and

Docker Compose version v2.2.3

Maybe 

```
<property>
    <name>dfs.client.read.shortcircuit</name>
    <value>false</value>
</property>
```

is the correct setting.

**Comment by Aalron** [comment] 2022-03-17 08:36
@fithisux hello , I have the same problem as you, have you solved it?

**Comment by packet23** [comment] 2022-03-18 21:35
Hey @fithisux and @Aalron - the docker-compose.yaml is tested against docker-compose >= 1.27 < 2.0. I can try reproducing with docker-compose 2.2.3 on Linux, but I don't have access to a macOS machine. What failures do you see?

**Comment by packet23** [comment] 2022-03-18 21:42
Alternatively, you can try installing docker-compose 1.x from [PyPI](https://pypi.org/project/docker-compose/).

**Comment by packet23** [comment] 2022-03-18 22:20
I cannot reproduce with Docker Engine 20.10 on Linux + docker-compose 2.2.3. I need more information:
* Could you attach the output of `docker compose logs`?
* Why do you suggest disabling short-circuit local reads (i.e. disabling `dfs.client.read.shortcircuit`) - did it fix the problem on your machine?

**Comment by packet23** [comment] 2022-03-18 23:34
@fithisux could you test the change from #2 on your machine?

**Comment by fithisux** [comment] 2022-03-21 14:02
I will test it tomorrow due to high volume of work.

**Comment by fithisux** [comment] 2022-03-23 08:50
> I cannot reproduce with Docker Engine 20.10 on Linux + docker-compose 2.2.3. I need more information:
> 
>     * Could you attach the output of `docker compose logs`?
> 
>     * Why do you suggest disabling short-circuit local reads (i.e. disabling `dfs.client.read.shortcircuit`) - did it fix the problem on your machine?

Yes it fixed it and was able to use the sandbox.

**Comment by fithisux** [comment] 2022-03-23 09:08
Hi @packet23  I QA'ed the fix and it works without issues. I mean the deployment starts without issues on _issue-1_.

If I switch to _main_ branch the issue appears again

`2022-03-23 09:05:29,502 INFO util.ExitUtil: Exiting with status 1: java.net.BindException: bind(2) error: Invalid argument when trying to bind to '/run/hadoop-hdfs/dn_socket'`

I used latest docker desktop on MacOS / Intel for the QA process

(I also have a vanilla docker-on-virtualbox via vagrant, that failed possibly because of misconfiguration, will try later to verify the fix there too)


See above @Aalron

**Comment by fithisux** [comment] 2022-03-23 10:53
Maybe there is a general permission problem cause when I use the second method, where the linux VM is running docker in Virtualbox I cannot seem to be able to write to /data fro hadoopnode

reference: https://stackoverflow.com/questions/56019914/docker-user-cannot-write-to-mounted-folder

**Comment by packet23** [comment] 2022-03-23 20:31
@fithisux thanks for verifying the PR. I'll merge the PR then, that will close this issue.

Feel free to create a separate issue for the virtualbox issue.

**Closed as completed** 2022-03-23 20:32 UTC
